-d C:\Users\Victor\Documents\Gitlab\PERSONAL GITHUB\uart\TangNano\impl\gwsynthesis\uart.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\Victor\Documents\Gitlab\PERSONAL GITHUB\uart\TangNano\GoWinUART.cst
-cfg C:\Users\Victor\Documents\Gitlab\PERSONAL GITHUB\uart\TangNano\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
